module.exports = {
  pessoaFisica: {
    tipo: 'Pessoa física',
    nome: 'Nome Física',
    CPF: '000.000.000-00',
    sexo: 'Masculino',
    dataNascimento: '01/01/0001',
    email: 'mail@mail.com',
    telefone: '(00) 9999-9999',
    celular: '(00) 99999-9999',
    foto: 'http://www.myphoto.com',
    endereco: [
      {
        endereco: 'Rua Abacaxi Trufado',
        numero: '100',
        complemento: '',
        bairro: 'Acidez',
        cidade: 'Fruta',
        estado: 'Comida',
        cep: '00000-000',
      },
    ],
  },
  pessoaFisicaMultiploEndereco: {
    tipo: 'Pessoa física',
    nome: 'Nome Física',
    CPF: '000.000.000-00',
    sexo: 'Masculino',
    dataNascimento: '01/01/0001',
    email: 'mail@mail.com',
    telefone: '(00) 9999-9999',
    celular: '(00) 99999-9999',
    foto: 'http://www.myphoto.com',
    endereco: [
      {
        endereco: 'Rua Abacaxi Trufado',
        numero: '100',
        complemento: '',
        bairro: 'Acidez',
        cidade: 'Fruta',
        estado: 'Comida',
        cep: '00000-000',
      },
      {
        endereco: 'Rua Abacaxi Trufado 2',
        numero: 1000,
        complemento: 'Abacaxi',
        bairro: 'Acidez',
        cidade: 'Fruta',
        estado: 'Comida',
        cep: '00000-001',
      },
    ],
  },
  pessoaFisicaErroCPF: {
    tipo: 'Pessoa física',
    nome: 'Nome Física',
    CPF: '00.000.000-00',
    sexo: 'Masculino',
    dataNascimento: '01/01/0001',
    email: 'mail@mail.com',
    telefone: '(00) 9999-9999',
    celular: '(00) 99999-9999',
    foto: 'http://www.myphoto.com',
    endereco: [
      {
        endereco: 'Rua Abacaxi Trufado',
        numero: '100',
        complemento: '',
        bairro: 'Acidez',
        cidade: 'Fruta',
        estado: 'Comida',
        cep: '00000-000',
      },
    ],
  },
  pessoaJuricaComCamposPessoaFisica: {
    tipo: 'Pessoa jurídica',
    nome: 'Nome Física',
    CPF: '000.000.000-00',
    sexo: 'Masculino',
    dataNascimento: '01/01/0001',
    email: 'mail@mail.com',
    telefone: '(00) 9999-9999',
    celular: '(00) 99999-9999',
    foto: 'http://www.myphoto.com',
    endereco: [
      {
        endereco: 'Rua Abacaxi Trufado',
        numero: '100',
        complemento: '',
        bairro: 'Acidez',
        cidade: 'Fruta',
        estado: 'Comida',
        cep: '00000-000',
      },
    ],
  },
  pessoaJurica: {
    tipo: 'Pessoa jurídica',
    nome: 'Nome Física',
    razaoSocial: 'Minha Razao Social',
    CNPJ: '00.000.000/0000-00',
    email: 'mail@mail.com',
    telefone: '(00) 9999-9999',
    celular: '(00) 99999-9999',
    foto: 'http://www.myphoto.com',
    endereco: [
      {
        endereco: 'Rua Abacaxi Trufado',
        numero: '100',
        complemento: '',
        bairro: 'Acidez',
        cidade: 'Fruta',
        estado: 'Comida',
        cep: '00000-000',
      },
    ],
  },
  pessoaJuricaErroCNPJ: {
    tipo: 'Pessoa jurídica',
    nome: 'Nome Física',
    razaoSocial: 'Minha Razao Social',
    CNPJ: '00.0.000/0000-00',
    email: 'mail@mail.com',
    telefone: '(00) 9999-9999',
    celular: '(00) 99999-9999',
    foto: 'http://www.myphoto.com',
    endereco: [
      {
        endereco: 'Rua Abacaxi Trufado',
        numero: '100',
        complemento: '',
        bairro: 'Acidez',
        cidade: 'Fruta',
        estado: 'Comida',
        cep: '00000-000',
      },
    ],
  },
};
